name: Release

on:
  push:
    branches: [ ci-testing ]
  pull_request:
    branches: [ ci-testing ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Tests
      run: sbt test

  release:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - name: Configure Secrets
#      shell: bash
#      env:
#        SONATYPE_CREDENTIALS: ${{ secrets.SONATYPE_CREDENTIALS }}
#        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
#      run: |
#        mkdir "$HOME/.sbt"
#        echo "$SONATYPE_CREDENTIALS" > "$HOME/.sbt/sonatype_credentials"
#        echo "$GPG_PRIVATE_KEY" > "$HOME/gpg_private_key"
#        gpg --import "$HOME/gpg_private_key"
#    - name: Publish
#      run: sbt release
    - name: Update Git Master Branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
        branch: ci-testing
    - name: Update Git Snapshots Branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
        branch: snapshots
