name: Release Snapshot

on:
  # https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/3
  # A PR merge always results in a push event so this means we basically want to
  # publish a snapshot when a PR is merged to snapshot. Rely on branch protections
  # to stop direct pushes to the snapshot branch.
  push:
    branches:
    - snapshot

jobs:
  test-snapshot-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Tests
      run: sbt test

  release-snapshot-branch:
    runs-on: ubuntu-latest
    needs:
    - test-snapshot-branch
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure Secrets
      shell: bash
      env:
        SONATYPE_CREDENTIALS: ${{ secrets.SONATYPE_CREDENTIALS }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        mkdir "$HOME/.sbt"
        echo "$SONATYPE_CREDENTIALS" > "$HOME/.sbt/sonatype_credentials"
        echo "$GPG_PRIVATE_KEY" > "$HOME/gpg_private_key"
        gpg --import "$HOME/gpg_private_key"
    - name: Publish
      run: sbt publish
