name: Release Master

on:
  # https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/3
  # A PR merge always results in a push event so this means we basically want to
  # publish a release when a PR is merged to master. Rely on branch protections
  # to stop direct pushes to the master branch.
  push:
    branches:
    - master

jobs:
  test-master-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run Tests
      run: sbt test

  release-master-branch:
    runs-on: ubuntu-latest
    # Do not run this job if the commit that was just pushed was the bump to a new SNAPSHOT
    # version. Otherwise we would get into a weird version bumping loop.
    if: "!contains(github.event.head_commit.message, 'SNAPSHOT')"
    needs:
    - test-master-branch
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set Up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Configure Secrets
      shell: bash
      env:
        SONATYPE_CREDENTIALS: ${{ secrets.SONATYPE_CREDENTIALS }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      run: |
        mkdir "$HOME/.sbt"
        echo "$SONATYPE_CREDENTIALS" > "$HOME/.sbt/sonatype_credentials"
        echo "$GPG_PRIVATE_KEY" > "$HOME/gpg_private_key"
        gpg --import "$HOME/gpg_private_key"
    - name: Publish
      run: sbt release
    - name: Update Master Branch Version
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
        branch: master
    - name: Update Snapshot Branch Version
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: true
        branch: snapshot
